# example workflow for Black Duck SCA scans using the Black Duck Security Scan Action
# https://github.com/marketplace/actions/black-duck-security-scan
name: bd-ss-action
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  blackduck:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v6
    - name: Setup Java JDK
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: temurin

    - name: Set up Python 3.14
      uses: actions/setup-python@v5
      with:
        python-version: "3.14"

    - name: Create virtualenv & install dependencies
      run: |
        python -m venv venv
        ./venv/bin/pip install --upgrade pip
        ./venv/bin/pip install -r requirements.txt

    - name: Check Python version (from venv)
      run: |
        ./venv/bin/python --version
        ./venv/bin/pip list

    - name: Black Duck SCA Scan
      uses: blackduck-inc/black-duck-security-scan@v2
      env:
        DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
      with:
        blackducksca_url: ${{ vars.BLACKDUCK_URL }}
        blackducksca_token: ${{ secrets.BLACKDUCK_TOKEN }}
        blackducksca_scan_failure_severities: BLOCKER
        detect_args: '--detect.excluded.detector.types=GIT --logging.level.detect=DEBUG'
        blackducksca_fixpr_enabled: true
        blackducksca_prComment_enabled: true
        blackducksca_reports_sarif_create: true
        blackducksca_upload_sarif_report: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        include_diagnostics: false
